name: Prueba Python

on: push

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependencia
        run: pip install pytest
      - name: Ejecutar pruebas
        run: pytest test.py
