name: Mi workflow ej 1

on: push


jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar librerias
        run: pip install pytest

      - name: Probar codigo
        run: pytest test.py
        

      
      
  

